=== edaa-org/IPXACT-Schema/ipxact-1.4/TGI/TGI.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp1 (http://www.altova.com) by Greg Ehmann (Philips Electronics Nederland BV) -->
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Mark Noll (Synopsys) -->
<xs:schema xmlns:tgi="http://www.spiritconsortium.org/XMLSchema/TGI" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.spiritconsortium.org/XMLSchema/TGI" elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:element name="callbacks">
		<xs:annotation>
			<xs:documentation>List of API callbacks</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="callback" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Defines a single callback in the API. The name attribute  defines the callback name and the group attribute is used to group similar calls in the generated documentation.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="description">
								<xs:annotation>
									<xs:documentation>Description of the callback.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="output">
								<xs:annotation>
									<xs:documentation>Defines the callback output. The argument type defaults to xsd:string if not specified. The argument name defaults to [type]Value where [type] is the argType value with the namespace designator removed.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="description" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Description of the output argument.</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="compatibleArgs" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="argName" type="xs:token" use="optional"/>
												<xs:attribute name="argType" type="xs:token" use="optional" default="xsd:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="argName" type="xs:token" use="optional"/>
									<xs:attribute name="argType" type="xs:token" use="optional" default="xsd:string"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="input" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Defines a callback input argument. The argument type defaults to xsd:string if not specified. The argument name defaults to [type]Value where [type] is the argType value with the namespace designator removed.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="description" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Description of the input argument.</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="compatibleArgs" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="argName" type="xs:token" use="optional"/>
												<xs:attribute name="argType" type="xs:token" use="optional" default="xsd:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="argName" type="xs:token" use="optional"/>
									<xs:attribute name="argType" type="xs:token" use="optional" default="xsd:string"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="compatibilityChange" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Specifies the API version at which this API call was modified. The modificationType attribute indicates the type of change. Valid changes types nclude: new -- implying an API call added in the specified version of the API, invalid -- implying that the specified call has been invalidated as of the specified version of the API, and modified -- implying that the API call functionality has been chagned as of the specified version of the API.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="modificationType" use="required">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="new"/>
														<xs:enumeration value="invalid"/>
														<xs:enumeration value="modified"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:token" use="required"/>
						<xs:attribute name="group" type="xs:string" use="optional" default="Default"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== edaa-org/IPXACT-Schema/ipxact-1.4/TGI/TGI.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Mark Noll (Synopsys) -->
<tgi:callbacks xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://www.spiritconsortium.org/XMLSchema/TGI/TGI.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tgi="http://www.spiritconsortium.org/XMLSchema/TGI">




<!-- DESIGN OPERATIONS -->
	<tgi:callback tgi:name="getDesignID" tgi:group="Design Operations">
		<tgi:description>get ID of the current or top design</tgi:description>
		<tgi:output tgi:argName="designID">
			<tgi:description>The ID of the current design or the top design if the 'top' argument is true.</tgi:description>
		</tgi:output>
		<tgi:input tgi:argName="top" tgi:argType="xsd:boolean"/>
	</tgi:callback>
	<tgi:callback tgi:name="getDesignVLNV" tgi:group="Design Operations">
		<tgi:description>Vendor Library Name Version of the design</tgi:description>
		<tgi:output tgi:argName="vlnvValue" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="designID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getDesignComponentInstanceIDs" tgi:group="Design Operations">
		<tgi:description>components instances IDs of the given design</tgi:description>
		<tgi:output tgi:argName="componentInstanceIDs" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="designID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getComponentInstanceID" tgi:group="Design Operations">
		<tgi:description>return the component instance ID of the named component instance in the given design</tgi:description>
		<tgi:output tgi:argName="componentInstanceID"/>
		<tgi:input tgi:argName="designID"/>
		<tgi:input tgi:argName="instanceName"/>
	</tgi:callback>

	<tgi:callback tgi:name="getDesignInterconnectionIDs" tgi:group="Design Operations">
		<tgi:description>List of interconnection element IDs</tgi:description>
		<tgi:output tgi:argName="interconnectionIDs" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="designID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getInterconnectionActiveInterfaces" tgi:group="Design Operations">
		<tgi:description>Returns the active interfaces as a list: componentID1 interfaceID1 componentID2 interfaceID2</tgi:description>
		<tgi:output tgi:argName="activeInterfaceValue" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="interconnectionID"/>
	</tgi:callback>

	<tgi:callback tgi:name="getDesignInterconnectionAbstractorInstanceIDs" tgi:group="Design Operations">
		<tgi:description>List of abstractor instances IDs for this interconnection</tgi:description>
		<tgi:output tgi:argName="abstractorInstanceIDs" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="interconnectName"/>
		<tgi:input tgi:argName="designID"/>
	</tgi:callback>

	<tgi:callback tgi:name="getDesignMonitorInterconnectionIDs" tgi:group="Design Operations">
		<tgi:description>List of monitorInterconnection element IDs</tgi:description>
		<tgi:output tgi:argName="monitorInterconnectionIDs" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="designID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getMonitorInterconnectionInterfaces" tgi:group="Design Operations">
		<tgi:description>Returns the active interface and monitor interfaces as a list in componentID interfaceID format, the active interface comes first in the list.</tgi:description>
		<tgi:output tgi:argName="interconnectInterfaceValue" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="monitorInterconnectionID"/>
	</tgi:callback>

	<tgi:callback tgi:name="getDesignAdHocConnectionIDs" tgi:group="Design Operations">
		<tgi:description>List of ad-hoc connection element IDs</tgi:description>
		<tgi:output tgi:argName="adHocConnectionIDs" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="designID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getAdHocConnectionTiedValue" tgi:group="Design Operations">
		<tgi:description>Get the tied value for an ad-hoc connection</tgi:description>
		<tgi:output tgi:argName="value"/>
		<tgi:input tgi:argName="adHocConnectionID" />
	</tgi:callback>
	<tgi:callback tgi:name="getAdHocConnectionInternalPortReferenceIDs" tgi:group="Design Operations">
		<tgi:description>List of internal ad-hoc port reference element IDs</tgi:description>
		<tgi:output tgi:argName="adHocInternalPortReferenceIDs" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="adHocConnectionID" />
	</tgi:callback>
	<tgi:callback tgi:name="getAdHocConnectionInternalPortReferenceDetails" tgi:group="Design Operations">
		<tgi:description>List for an internal connection containing the componentRef, portRef, left, and right attribute values</tgi:description>
		<tgi:output tgi:argName="details" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="adHocInternalPortReferenceID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getAdHocConnectionExternalPortReferenceIDs" tgi:group="Design Operations">
		<tgi:description>List of external ad-hoc port reference element IDs</tgi:description>
		<tgi:output tgi:argName="adHocExternalPortReferenceIDs" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="adHocConnectionID" />
	</tgi:callback>
	<tgi:callback tgi:name="getAdHocConnectionExternalPortDetails" tgi:group="Design Operations">
		<tgi:description>List for an external connection containing the portRef, left, and right attribute values</tgi:description>
		<tgi:output tgi:argName="details" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="adHocExternalPortReferenceID"/>
	</tgi:callback>

	<tgi:callback tgi:name="getDesignHierConnectionIDs" tgi:group="Design Operations">
		<tgi:description>List of hierarchical connection element IDs</tgi:description>
		<tgi:output tgi:argName="hierConnectionIDs" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="designID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getHierConnectionDetails" tgi:group="Design Operations">
		<tgi:description>List containing the interface name, component reference, and interface reference</tgi:description>
		<tgi:output tgi:argName="values" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="hierConnectionID"/>
	</tgi:callback>





<!-- COMPONENT INSTANCE OPERATIONS -->
	<tgi:callback tgi:name="getComponentInstanceName" tgi:group="Component Instance Operations">
		<tgi:description>Instance name of the component</tgi:description>
		<tgi:output tgi:argName="value"/>
		<tgi:input tgi:argName="componentInstanceID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getComponentInstanceVLNV" tgi:group="Component Instance Operations">
		<tgi:description>Vendor Library Name Version of the component (from the design file)</tgi:description>
		<tgi:output tgi:argName="vlnvValue" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="componentInstanceID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getComponentInstanceComponentID" tgi:group="Component Instance Operations">
		<tgi:description>ID for the component associated with given instance (crossing from design to component file)</tgi:description>
		<tgi:output tgi:argName="componentID"/>
		<tgi:input tgi:argName="componentInstanceID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getComponentInstanceConfigurableElementIDs" tgi:group="Component Instance Operations">
		<tgi:description>configurable elements IDs of the given component instance, the use of this function is not recommended</tgi:description>
		<tgi:output tgi:argName="configurableElementIDs" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="componentInstanceID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getComponentInstanceXML" tgi:group="Component Instance Operations">
		<tgi:description>Return the component XML in text format. Schema version is DE dependent.</tgi:description>
		<tgi:output tgi:argName="xmlText"/>
		<tgi:input tgi:argName="componentInstanceID"/>
	</tgi:callback>






<!-- ABSTRACTOR INSTANCE OPERATIONS -->
	<tgi:callback tgi:name="getAbstractorInstanceName" tgi:group="Abstractor Instance Operations">
		<tgi:description>Instance name of the abstractor</tgi:description>
		<tgi:output tgi:argName="value"/>
		<tgi:input tgi:argName="abstractorInstanceID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getAbstractorInstanceVLNV" tgi:group="Abstractor Instance Operations">
		<tgi:description>Vendor Library Name Version of the abstractor (from the design file)</tgi:description>
		<tgi:output tgi:argName="vlnvValue" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="abstractorInstanceID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getAbstractorInstanceAbstractorID" tgi:group="Abstractor Instance Operations">
		<tgi:description>ID for the abstractor associated with given instance (crossing from design configuration to abstractor file)</tgi:description>
		<tgi:output tgi:argName="abstractorID"/>
		<tgi:input tgi:argName="abstractorInstanceID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getAbstractorInstanceConfigurableElementIDs" tgi:group="Abstractor Instance Operations">
		<tgi:description>configurable elements IDs of the given abstractor instance, the use of this function is not recommended.</tgi:description>
		<tgi:output tgi:argName="configurableElementIDs" tgi:argType="spirit:soapStringArrayType"/>
		<tgi:input tgi:argName="abstractorInstanceID"/>
	</tgi:callback>
	<tgi:callback tgi:name="getAbstractorInstanceXML" tgi:group="Abstractor Instance Operations">
		<tgi:description>Return the abstractor XML in text format. Schema version is DE dependent.</tgi:description>
		<tgi:output tgi:argName="xmlText"/>
		<tgi:input tgi:argName="abstractorInstanceID"/>
	</tgi:callback>



<!-- INTERFACE OPERATIONS -->
	<tgi:callback tgi:name="getInterfaceBusTypeVLNV" tgi:group="Interface Operations">
		<tgi:description>List of VLNV of the bus definition</tgi:description>
